"""Rocket ascent environment support package."""

from .physics import (
    DEFAULT_CONFIG,
    PhysicsConfig,
    PhysicsStep,
    RocketState,
    ambient_pressure,
    altitude,
    atmosphere_density,
    burn_fuel,
    circular_orbit_velocity,
    decompose_velocity,
    drag_acceleration,
    gravity_acceleration,
    map_bounded_action,
    map_normalized_action,
    mass_from_fuel,
    radial_unit,
    sea_level_engine_vacuum_efficiency,
    step_dynamics,
    tangential_unit,
    thrust_acceleration,
    thrust_direction,
)
from .env import EnvConfig, RocketAscentEnv
from .observations import Observation, RocketGoal, RocketObservation

__all__ = [
    "DEFAULT_CONFIG",
    "EnvConfig",
    "Observation",
    "PhysicsConfig",
    "PhysicsStep",
    "RocketGoal",
    "RocketState",
    "RocketObservation",
    "RocketAscentEnv",
    "ambient_pressure",
    "altitude",
    "atmosphere_density",
    "burn_fuel",
    "circular_orbit_velocity",
    "decompose_velocity",
    "drag_acceleration",
    "gravity_acceleration",
    "map_bounded_action",
    "map_normalized_action",
    "mass_from_fuel",
    "radial_unit",
    "sea_level_engine_vacuum_efficiency",
    "step_dynamics",
    "tangential_unit",
    "thrust_acceleration",
    "thrust_direction",
]
